- name: Download and Execute Shell Script from GitHub
  hosts: all
  become: yes
  tasks:

    - name: Download the Shell Script from GitHub
      get_url:
        url: "https://raw.githubusercontent.com/karthikrepo123/kkrepo/refs/heads/main/kkscript.sh"
        dest: "/tmp/kkscript.sh"
        mode: '0755'

    - name: Execute the Shell Script
      shell: "/tmp/kkscript.sh"
      args:
        chdir: "/tmp"
        creates: "/tmp/kkscript.sh"

    - name: Clean up the Shell Script (optional)
      file:
        path: "/tmp/kkscript.sh"
        state: absent
